// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdzEPwLEIdSf0BuACa3Oh0m_VcTGzEi0',
    appId: '1:533328896608:web:77d381a3f133a7cfce9905',
    messagingSenderId: '533328896608',
    projectId: 'laboratoriska-firebase-cetvrta',
    authDomain: 'laboratoriska-firebase-cetvrta.firebaseapp.com',
    storageBucket: 'laboratoriska-firebase-cetvrta.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MnZNIYlhV0eIQb1Ye1-dQNrIXHpCUyg',
    appId: '1:533328896608:android:efddf03a908cf284ce9905',
    messagingSenderId: '533328896608',
    projectId: 'laboratoriska-firebase-cetvrta',
    storageBucket: 'laboratoriska-firebase-cetvrta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiZRidUNhet4APyALuISNwujO777Khb0',
    appId: '1:533328896608:ios:f16da7720c2a8133ce9905',
    messagingSenderId: '533328896608',
    projectId: 'laboratoriska-firebase-cetvrta',
    storageBucket: 'laboratoriska-firebase-cetvrta.firebasestorage.app',
    iosBundleId: 'com.example.misL4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAiZRidUNhet4APyALuISNwujO777Khb0',
    appId: '1:533328896608:ios:f16da7720c2a8133ce9905',
    messagingSenderId: '533328896608',
    projectId: 'laboratoriska-firebase-cetvrta',
    storageBucket: 'laboratoriska-firebase-cetvrta.firebasestorage.app',
    iosBundleId: 'com.example.misL4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKdzEPwLEIdSf0BuACa3Oh0m_VcTGzEi0',
    appId: '1:533328896608:web:58d1d3c354bfc92cce9905',
    messagingSenderId: '533328896608',
    projectId: 'laboratoriska-firebase-cetvrta',
    authDomain: 'laboratoriska-firebase-cetvrta.firebaseapp.com',
    storageBucket: 'laboratoriska-firebase-cetvrta.firebasestorage.app',
  );
}
